service: rooom

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  deploymentBucket:
    name: boristane-lambdas-deployments
  region: eu-west-2
  logRetentionInDays: 7
  versionFunctions: false

package:
  exclude:
    - .cache/**
    - .env


functions:
  server:
    handler: .build/serverless.server
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'